services:
  formulacountdown:
    build: .
    container_name: 'formulacountdown-sveltekit'
    restart: 'always'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.formulacountdown.rule: 'Host(`formulacountdown.com`) || Host(`www.formulacountdown.com`)'
      traefik.http.routers.formulacountdown.entrypoints: 'websecure'
      traefik.http.routers.formulacountdown.tls: 'true'
      traefik.http.routers.formulacountdown.tls.certresolver: 'hetzner'
    networks:
      - formulacountdown-proxy

networks:
  formulacountdown-proxy:
    name: formulacountdown-proxy
    external: true
